In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd

df = pd.read_csv('/content/gdrive/My Drive/ip_files/data/outliers.csv')
print(df.shape)

(82, 22251)


Split into data and classes

In [0]:
X = df.loc[:, df.columns != 'class']
y = df['class']

## Classification

Let's load some of the best models and classify outliers on them.

In [0]:
from joblib import load
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score
import numpy as np

clf = load('/content/gdrive/My Drive/ip_files/models/svm_balanced_poly_C300_gamaScale_degree1.pkl')
predicted = clf.predict(X)

print('accuracy: {}'.format(np.round(accuracy_score(y, predicted), 4)))
print('recall score: \n{}'.format(np.round(recall_score(y, predicted, average=None), 4)))
print('precision score: \n{}'.format(np.round(precision_score(y, predicted, average=None), 4)))
print('confusion matrix: \n{}'.format(confusion_matrix(y, predicted)))


accuracy: 0.7683
recall score: 
[0.7143 0.     0.75   0.8065 0.8636 0.8333 0.5455]
precision score: 
[0.7143 0.     0.75   0.8333 0.95   0.5556 0.6667]
confusion matrix: 
[[ 5  0  0  0  0  1  1]
 [ 0  0  0  1  0  0  0]
 [ 0  0  3  1  0  0  0]
 [ 0  3  1 25  1  0  1]
 [ 0  0  0  3 19  0  0]
 [ 0  0  0  0  0  5  1]
 [ 2  0  0  0  0  3  6]]


In [0]:
from joblib import load
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score
import numpy as np

clf = load('/content/gdrive/My Drive/ip_files/models/svm_balanced_rbf_C300_gamaScale.pkl')
predicted = clf.predict(X)

print('accuracy: {}'.format(np.round(accuracy_score(y, predicted), 4)))
print('recall score: \n{}'.format(np.round(recall_score(y, predicted, average=None), 4)))
print('precision score: \n{}'.format(np.round(precision_score(y, predicted, average=None), 4)))
print('confusion matrix: \n{}'.format(confusion_matrix(y, predicted)))

accuracy: 0.7317
recall score: 
[0.7143 0.     0.25   0.8065 0.8636 0.6667 0.5455]
precision score: 
[0.4167 0.     0.25   0.8333 0.9048 0.5714 0.8571]
confusion matrix: 
[[ 5  0  0  0  0  1  1]
 [ 1  0  0  0  0  0  0]
 [ 1  0  1  2  0  0  0]
 [ 1  1  2 25  2  0  0]
 [ 0  0  1  2 19  0  0]
 [ 2  0  0  0  0  4  0]
 [ 2  0  0  1  0  2  6]]


In [0]:
from joblib import load
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score
import numpy as np

clf = load('/content/gdrive/My Drive/ip_files/models/svm_sampled_class2_400_rbf_C300_gamaScale.pkl')
predicted = clf.predict(X)

print('accuracy: {}'.format(np.round(accuracy_score(y, predicted), 4)))
print('recall score: \n{}'.format(np.round(recall_score(y, predicted, average=None), 4)))
print('precision score: \n{}'.format(np.round(precision_score(y, predicted, average=None), 4)))
print('confusion matrix: \n{}'.format(confusion_matrix(y, predicted)))

accuracy: 0.7073
recall score: 
[0.7143 0.     0.25   0.7742 0.8182 0.6667 0.5455]
precision score: 
[0.5    0.     0.25   0.7742 0.9474 0.5714 0.8571]
confusion matrix: 
[[ 5  0  0  0  0  1  1]
 [ 0  0  0  1  0  0  0]
 [ 0  0  1  3  0  0  0]
 [ 1  3  2 24  1  0  0]
 [ 0  1  1  2 18  0  0]
 [ 2  0  0  0  0  4  0]
 [ 2  0  0  1  0  2  6]]


In [0]:
from joblib import load
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score
import numpy as np

clf = load('/content/gdrive/My Drive/ip_files/models/svm_sampled_class2_400_poly_C300_gamaScale_degree1s.pkl')
predicted = clf.predict(X)

print('accuracy: {}'.format(np.round(accuracy_score(y, predicted), 4)))
print('recall score: \n{}'.format(np.round(recall_score(y, predicted, average=None), 4)))
print('precision score: \n{}'.format(np.round(precision_score(y, predicted, average=None), 4)))
print('confusion matrix: \n{}'.format(confusion_matrix(y, predicted)))

accuracy: 0.7195
recall score: 
[0.7143 0.     0.5    0.7742 0.7727 0.8333 0.5455]
precision score: 
[0.7143 0.     0.6667 0.8276 0.9444 0.5556 0.75  ]
confusion matrix: 
[[ 5  0  0  0  0  1  1]
 [ 0  0  0  1  0  0  0]
 [ 0  1  2  1  0  0  0]
 [ 0  5  1 24  1  0  0]
 [ 0  2  0  3 17  0  0]
 [ 0  0  0  0  0  5  1]
 [ 2  0  0  0  0  3  6]]
